### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by scpeters** [davidfischinger/haf_grasping#1]
Which open source license are you applying to this code? I didn't see a LICENSE file or anything in the header or source files indicating a license.

http://wiki.ros.org/DevelopersGuide#Licensing

Looks like cool software!

**Comment by davidfischinger** [comment]
I added a LICENSE file => BSD 

Thank you.

**Comment by scpeters** [comment]
Thanks! Do you want to update the package.xml too?

https://github.com/davidfischinger/haf_grasping/blob/master/package.xml#L13

**Comment by davidfischinger** [comment]
Done. Thank you.
Regards,
David

2015-10-28 18:15 GMT+01:00 Steven Peters notifications@github.com:

> Thanks! Do you want to update the package.xml too?
> 
> https://github.com/davidfischinger/haf_grasping/blob/master/package.xml#L13
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davidfischinger/haf_grasping/issues/1#issuecomment-151914131
> .

## 

Dr. David Fischinger
Vienna University of Technology
Automation & Control Institute
Gusshausstr. 27/376
1040 Vienna, Austria, Europe
Phone: +43 158801 376622
fischinger@acin.tuwien.ac.at
