### ISSUE TITLE
Potential vulnerability: topic from ROS parameters

### ISSUE THREAD

**Issue by tandf** [davidfischinger/haf_grasping#8]
Hi,

We notice that you are using a topic name from ROS parameter at the following locations:
https://github.com/davidfischinger/haf_grasping/blob/0e7bcd7abcb74d0fdf637d32d81b43675ccb91c7/src/calc_grasppoints_action_client.cpp#L124
For security reasons detailed below, we strongly suggest avoiding the usage of strings from parameters as topic names.

Although parameters are usually set in parameter files, they can also be changed by nodes. Specifically, other nodes in the same ROS application can also change the parameters listed above before it’s used, either by accident or *intentionally* (i.e., by potential attackers). Such changes can lead to denial-of-service since the action client fails to subscribe to the correct input pointcloud topic. What’s worse, if an attacker exists, she can even launch man-in-the-middle attacks by first fooling the action client to subscribe to a fake topic e.g. `/points_in_lcs_fake`, then sending messages received from `/haf_grasping/depth_registered/single_cloud/points_in_lcs` to `/points_in_lcs_fake` after modifying the contents. In these two cases, haf_grasping cannot get the pointcloud of the unknown object and therefore cannot calculate grasp points, or even generate wrong grasp points which can lead to failures of grasping objects. Because ROS is an OSS (open-source software) community, third-party nodes are widely used in ROS applications, usually without complete vetting of their behavior, which gives the opportunity to potentially malicious actors to inject malicious code (e.g, by submitting hypocrite commits like in other OSS systems [1]) to infiltrate the ROS applications that use it (or software supply chain attacks, one of the primary means for real-world attackers today [2]).

We understand that using parameters to set topic names brings flexibility. Still, for the purpose of security, we strongly suggest that you avoid such vulnerable programming patterns if possible. For example, to avoid the exposure of this specific vulnerability, you may consider alternatives like remapping, which is designed for configuring names when launching the nodes.

[1] Q. Wu and K. Lu, “On the feasibility of stealthily introducing vulnerabilities in open-source software via hypocrite commits,” 2021, https://linuxreviews.org/images/d/d9/OpenSourceInsecurity.pdf.
[2] Supply chain attacks are the hacker’s new favourite weapon. and the threat is getting bigger. https://www.zdnet.com/article/supply-chain-attacks-are-the-hackers-new-favourite-weapon-and-the-threat-is-getting-bigger/.

**Comment by tandf** [comment]
Hi there, I wanted to follow up on this security vulnerability. Could you please let me know if there have been any updates or concerns regarding this issue? Thanks

**Comment by davidfischinger** [comment]
Hi ,
thanks for the reminder (your last email came one day after my son was
born…).
I will check until the weekend.
BR David Fischinger

Yunpeng Luo ***@***.***> schrieb am So. 26. März 2023 um
23:28:

> Hi there, I wanted to follow up on this security vulnerability. Could you
> please let me know if there have been any updates or concerns regarding
> this issue? Thanks
>

**Comment by davidfischinger** [comment]
Hi there,
hope it is fixed now.

**Comment by tandf** [comment]
Hi David, congratulations on the birth of your son! Thanks for the fix, that looks great, and I'm closing this issue
